import {
  eachHourOfInterval,
  endOfDay,
  format,
  setHours,
  startOfDay,
} from "date-fns";
import Head from "next/head";
import React, { useState } from "react";
import EventCard from "~/components/EventCard";
import { type Event } from "~/types";

export default function Home() {
  const hours = eachHourOfInterval({
    start: startOfDay(new Date()),
    end: endOfDay(new Date()),
  });

  const [events, setEvents] = useState<Event[]>([
    {
      id: "1",
      start: setHours(startOfDay(new Date()), 2),
      end: setHours(startOfDay(new Date()), 8),
      description: "First",
    },
    {
      id: "2",
      start: setHours(startOfDay(new Date()), 1),
      end: setHours(startOfDay(new Date()), 4),
      description: "Second",
    },
    {
      id: "3",
      start: setHours(startOfDay(new Date()), 2),
      end: setHours(startOfDay(new Date()), 5),
      description: "Third",
    },
    {
      id: "4",
      start: setHours(startOfDay(new Date()), 6),
      end: setHours(startOfDay(new Date()), 9),
      description: "Fourth",
    },
    {
      id: "5",
      start: setHours(startOfDay(new Date()), 9),
      end: setHours(startOfDay(new Date()), 10),
      description: "Fifth",
    },
  ]);

  return (
    <>
      <Head>
        <title>Planner 2 - twice the fun</title>
        <meta name="description" content="Generated by create-t3-app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <div id="agenda" className="relative p-4">
        {hours.map((hour, i) => (
          <div key={i} className="flex border-t">
            <div className="flex h-16 w-12 flex-col pr-1 text-right">
              <span className="-mb-2">{format(hour, "HH:mm")}</span>
              <span className="text-grey text-xs">:15</span>
              <span className="text-grey text-xs">:30</span>
              <span className="text-grey text-xs">:45</span>
            </div>
            <div className="flex-1"></div>
          </div>
        ))}

        {events.map((event) => (
          <EventCard key={event.id} event={event} />
        ))}
      </div>
    </>
  );
}
