import {
  eachHourOfInterval,
  endOfDay,
  format,
  getHours,
  setHours,
  startOfDay,
} from "date-fns";
import Head from "next/head";
import { useEffect, useRef, useState } from "react";
import EventCard from "~/components/EventCard";
import { type Event, type Timeslot } from "~/types";

export default function Home() {
  const hours = eachHourOfInterval({
    start: startOfDay(new Date()),
    end: endOfDay(new Date()),
  });
  // hours render the slots on the screen, timeslots track pixel specific locations
  // for drag and resize and laying out of events
  const [timeslots, setTimeslots] = useState<Timeslot[]>([]);

  useEffect(() => {
    handleTimeslots();
  }, []);

  const handleTimeslots = () => {
    const calculatedTimeslots: Timeslot[] = [];
    const timeslotDivs = document.querySelectorAll("[data-timeslot") as unknown;

    (timeslotDivs as HTMLDivElement[]).forEach((timeslotDiv) => {
      if (!timeslotDiv.dataset.timeslot) {
        throw new Error(
          "Missing timeslot data, data attribute does not contain a value",
        );
      }
      const hour = parseInt(timeslotDiv.dataset.timeslot);
      calculatedTimeslots.push({
        hour,
        date: setHours(startOfDay(new Date()), hour),
        top: timeslotDiv.getBoundingClientRect().top,
        bottom:
          timeslotDiv.getBoundingClientRect().top +
          timeslotDiv.getBoundingClientRect().height,
      });
    });
    console.dir({ calculatedTimeslots });
    setTimeslots(calculatedTimeslots);
  };

  const [events, setEvents] = useState<Event[]>([
    {
      id: "1",
      start: setHours(startOfDay(new Date()), 2),
      end: setHours(startOfDay(new Date()), 8),
      description: "First",
    },
    {
      id: "2",
      start: setHours(startOfDay(new Date()), 1),
      end: setHours(startOfDay(new Date()), 4),
      description: "Second",
    },
    {
      id: "3",
      start: setHours(startOfDay(new Date()), 2),
      end: setHours(startOfDay(new Date()), 5),
      description: "Third",
    },
    {
      id: "4",
      start: setHours(startOfDay(new Date()), 6),
      end: setHours(startOfDay(new Date()), 9),
      description: "Fourth",
    },
    {
      id: "5",
      start: setHours(startOfDay(new Date()), 9),
      end: setHours(startOfDay(new Date()), 10),
      description: "Fifth",
    },
  ]);

  const calculateHourBasedOnPosition = (clientY: number) => {
    const clientYOffset = clientY - agendaTopOffset;
    const timeslot = timeslots?.find(
      (timeslot) =>
        timeslot.top <= clientYOffset && timeslot.bottom >= clientYOffset,
    );

    return timeslot?.hour;
  };

  const calculatePositionBaseOnHour = (start: Date, end: Date) => {
    // console.dir({ start, end });
    const firstTimeslot = timeslots.find(
      (timeslot) => timeslot.hour === getHours(start),
    );
    const secondTimeslot = timeslots.find(
      (timeslot) => timeslot.hour === getHours(end),
    );

    // timeslots not found, default to the top of the agenda
    if (!firstTimeslot || !secondTimeslot) {
      return { top: agendaTopOffset, bottom: agendaTopOffset };
    }

    return {
      top: firstTimeslot.top - agendaTopOffset,
      bottom: secondTimeslot.top - agendaTopOffset,
    };
  };

  const handleEventUpdate = (start: Date, end: Date, eventId: string) => {
    setEvents((prev) => {
      return prev.map((prevEvent) =>
        prevEvent.id === eventId
          ? {
              ...prevEvent,
              start,
              end,
            }
          : prevEvent,
      );
    });
  };

  // when calculating hour or top/bottom of timeslots you have to take into account the top position
  // of the agenda. This is because drag and resize send Y coordinate of cursor on the screen which
  // then has to be offset by the agenda's top position to be accurate
  const agendaRef = useRef<HTMLDivElement | null>(null);
  const [agendaTopOffset, setAgendaTopOffset] = useState(0);
  useEffect(() => {
    if (agendaRef) {
      // TODO: discovered that this isn't working, returns 0
      console.log(agendaRef.current?.clientTop);
      const agendaTop = agendaRef.current?.getBoundingClientRect().top ?? 0;
      setAgendaTopOffset(agendaTop);
    }
  }, [agendaRef]);

  return (
    <>
      <Head>
        <title>Planner 2 - twice the fun</title>
        <meta name="description" content="Generated by create-t3-app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <div ref={agendaRef} className="flex px-4 py-8">
        {/* Draw agenda slot headers (shows the time for each slow, displayed on the left or head of slot) */}
        <div className="flex flex-col">
          {hours.map((hour) => (
            <div
              key={hour.toISOString()}
              data-timeslot={format(hour, "H")}
              className="flex"
            >
              <div className="border-grey/30 flex h-20 w-16 flex-col items-end border-t pr-1">
                <span className="-mb-1">{format(hour, "HH:mm")}</span>
                <span className="text-grey hidden text-sm">:15</span>
                <span className="text-grey hidden text-sm">:30</span>
                <span className="text-grey hidden text-sm">:45</span>
              </div>
            </div>
          ))}
        </div>

        {/* Draw agenda slots */}
        <div className="relative flex flex-1 flex-col">
          {hours.map((hour) => (
            <div key={hour.toISOString()} className="flex">
              <div className="border-grey/30 flex h-20 flex-1 items-center justify-center border-t"></div>
            </div>
          ))}

          {/* Draw events */}
          {events.map((event) => (
            <EventCard
              key={event.id}
              event={event}
              handleEventUpdate={handleEventUpdate}
              timeslots={timeslots}
              calculateHourBasedOnPosition={calculateHourBasedOnPosition}
              calculatePositionBaseOnHour={calculatePositionBaseOnHour}
            />
          ))}
        </div>
      </div>
    </>
  );
}
